# ----
# Site

title: Kapela Cmaj7
url: "https://www.kapela-cmaj7.cz"
baseurl:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.svg
description: Informace, budouci koncerty a kontakt kapely Cmaj7.
author:
  name: Kapela Cmaj7
  email: kapela.cmaj7@gmail.com
  instagram: _cmaj7__
  youtube: "@kapelaCmaj7"
social:
  name: Kapela Cmaj7
  links:
    - https://www.youtube.com/@kapelaCmaj7
    - https://www.instagram.com/_cmaj7__/
    - https://www.facebook.com/kapelacmaj7/

# -----
# Build

timezone: Europe/Prague

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - flake.nix
  - flake.lock

collections:
  band_members:

jekyll-archives:
  enabled: ["categories"]

defaults:
  - scope:
      path: ""
      type: "band_members"
    values: {}
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "contact-success.html"
    values:
      layout: "page"

# Social icons available in footer
social_icons:
  - Facebook
  - Instagram
  - Email
